version: '3'
services:

  gitpod:
    image: eu.gcr.io/gitpod-core-dev/build/gitpod-k3s:${VERSION:-latest}
    privileged: true
    # tmpfs:
    #   - /run
    #   - /var/run
    #   - /var/gitpod/workspaces
    volumes:
      - ./values:/values
      # - ./certs:/certs
    ports:
      - 443:443
      - 80:80
    environment:
      - DOMAIN=${DOMAIN}
      - DNSSERVER=${DNSSERVER:-}
      - GITPOD_CHART_VERSION=${GITPOD_CHART_VERSION:-}
