version: '3'
services:

  proxy:
    image: nginx
    volumes:
      - ./certs:/etc/nginx/certs
      - ./proxy/default.conf:/etc/nginx/templates/default.conf.template
    ports:
      - 443:443
    environment:
      - BASEDOMAIN=${BASEDOMAIN}
    depends_on:
      - gitpod
      - gitlab

  gitpod:
    image: eu.gcr.io/gitpod-core-dev/build/gitpod-k3s:${VERSION:-latest}
    privileged: true
    tmpfs:
      - /run
      - /var/run
      - /var/gitpod/workspaces
    volumes:
      - ./values:/values
      - ./certs:/certs
    environment:
      - BASEDOMAIN=${BASEDOMAIN}
      - DNSSERVER=${DNSSERVER:-}
      - GITPOD_CHART_VERSION=${GITPOD_CHART_VERSION:-}

  gitlab:
    image: eu.gcr.io/gitpod-core-dev/build/gitlab-k3s:${VERSION:-latest}
    privileged: true
    tmpfs:
      - /run
      - /var/run
    volumes:
      - ./certs:/certs
    environment:
      - BASEDOMAIN=${BASEDOMAIN}
      - DNSSERVER=${DNSSERVER:-}
