packages:
  - name: docker
    type: docker
    srcs:
      - entrypoint.sh
      - gitpod-helm-installer.yaml
      - values.yaml
    deps:
      - chart:helm
    argdeps:
      - version
    config:
      dockerfile: Dockerfile
      image:
        - ${imageRepoBase}/gitpod-k3s:${version}
